// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addJobTags = `-- name: AddJobTags :exec
UPDATE jobs
SET tags = (SELECT ARRAY(SELECT DISTINCT unnest(tags || $1::text[]))),
    updated_at = now()
WHERE id = $2
`

type AddJobTagsParams struct {
	NewTags []string  `json:"new_tags"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) AddJobTags(ctx context.Context, arg AddJobTagsParams) error {
	_, err := q.db.Exec(ctx, addJobTags, arg.NewTags, arg.ID)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (external_reference, job_type, status, input, metadata, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, external_reference, job_type, status, progress_step, progress_current, progress_total, progress_message, progress_updated_at, error, input, output, metadata, tags, created_at, updated_at
`

type CreateJobParams struct {
	ExternalReference string          `json:"external_reference"`
	JobType           string          `json:"job_type"`
	Status            string          `json:"status"`
	Input             json.RawMessage `json:"input"`
	Metadata          json.RawMessage `json:"metadata"`
	Tags              []string        `json:"tags"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ExternalReference,
		arg.JobType,
		arg.Status,
		arg.Input,
		arg.Metadata,
		arg.Tags,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalReference,
		&i.JobType,
		&i.Status,
		&i.ProgressStep,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.ProgressMessage,
		&i.ProgressUpdatedAt,
		&i.Error,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeJob = `-- name: FinalizeJob :execrows
UPDATE jobs
SET status = $1, error = $2, output = $3, tags = $4, updated_at = now()
WHERE id = $5 AND status NOT IN ('completed', 'failed', 'cancelled')
`

type FinalizeJobParams struct {
	Status string          `json:"status"`
	Error  string          `json:"error"`
	Output json.RawMessage `json:"output"`
	Tags   []string        `json:"tags"`
	ID     uuid.UUID       `json:"id"`
}

func (q *Queries) FinalizeJob(ctx context.Context, arg FinalizeJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeJob,
		arg.Status,
		arg.Error,
		arg.Output,
		arg.Tags,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, external_reference, job_type, status, progress_step, progress_current, progress_total, progress_message, progress_updated_at, error, input, output, metadata, tags, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalReference,
		&i.JobType,
		&i.Status,
		&i.ProgressStep,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.ProgressMessage,
		&i.ProgressUpdatedAt,
		&i.Error,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByExternalReference = `-- name: GetJobByExternalReference :one
SELECT id, external_reference, job_type, status, progress_step, progress_current, progress_total, progress_message, progress_updated_at, error, input, output, metadata, tags, created_at, updated_at FROM jobs WHERE external_reference = $1
`

func (q *Queries) GetJobByExternalReference(ctx context.Context, externalReference string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByExternalReference, externalReference)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ExternalReference,
		&i.JobType,
		&i.Status,
		&i.ProgressStep,
		&i.ProgressCurrent,
		&i.ProgressTotal,
		&i.ProgressMessage,
		&i.ProgressUpdatedAt,
		&i.Error,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobTags = `-- name: GetJobTags :one
SELECT tags FROM jobs WHERE id = $1
`

func (q *Queries) GetJobTags(ctx context.Context, id uuid.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getJobTags, id)
	var tags []string
	err := row.Scan(&tags)
	return tags, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, external_reference, job_type, status, progress_step, progress_current, progress_total, progress_message, progress_updated_at, error, input, output, metadata, tags, created_at, updated_at FROM jobs
WHERE ($1::text[] IS NULL OR tags @> $1::text[])
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListJobsParams struct {
	Tags         []string `json:"tags"`
	ResultOffset int32    `json:"result_offset"`
	ResultLimit  int32    `json:"result_limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Tags, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ExternalReference,
			&i.JobType,
			&i.Status,
			&i.ProgressStep,
			&i.ProgressCurrent,
			&i.ProgressTotal,
			&i.ProgressMessage,
			&i.ProgressUpdatedAt,
			&i.Error,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportProgress = `-- name: ReportProgress :exec
UPDATE jobs
SET status = 'running',
    progress_step = $1,
    progress_current = $2,
    progress_total = $3,
    progress_message = $4,
    progress_updated_at = now(),
    tags = $5,
    updated_at = now()
WHERE id = $6
`

type ReportProgressParams struct {
	ProgressStep    string    `json:"progress_step"`
	ProgressCurrent int32     `json:"progress_current"`
	ProgressTotal   int32     `json:"progress_total"`
	ProgressMessage string    `json:"progress_message"`
	Tags            []string  `json:"tags"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) ReportProgress(ctx context.Context, arg ReportProgressParams) error {
	_, err := q.db.Exec(ctx, reportProgress,
		arg.ProgressStep,
		arg.ProgressCurrent,
		arg.ProgressTotal,
		arg.ProgressMessage,
		arg.Tags,
		arg.ID,
	)
	return err
}
