// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID                uuid.UUID          `json:"id"`
	ExternalReference string             `json:"external_reference"`
	JobType           string             `json:"job_type"`
	Status            string             `json:"status"`
	ProgressStep      string             `json:"progress_step"`
	ProgressCurrent   int32              `json:"progress_current"`
	ProgressTotal     int32              `json:"progress_total"`
	ProgressMessage   string             `json:"progress_message"`
	ProgressUpdatedAt pgtype.Timestamptz `json:"progress_updated_at"`
	Error             string             `json:"error"`
	Input             json.RawMessage    `json:"input"`
	Output            json.RawMessage    `json:"output"`
	Metadata          json.RawMessage    `json:"metadata"`
	Tags              []string           `json:"tags"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type JobStep struct {
	ID          uuid.UUID          `json:"id"`
	JobID       uuid.UUID          `json:"job_id"`
	Name        string             `json:"name"`
	Sequence    int32              `json:"sequence"`
	Status      string             `json:"status"`
	Error       string             `json:"error"`
	Input       json.RawMessage    `json:"input"`
	Output      json.RawMessage    `json:"output"`
	StartedAt   time.Time          `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}
