// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: steps.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const completeStep = `-- name: CompleteStep :exec
UPDATE job_steps
SET status = 'completed', output = $1, completed_at = now(), updated_at = now()
WHERE id = $2
`

type CompleteStepParams struct {
	Output json.RawMessage `json:"output"`
	ID     uuid.UUID       `json:"id"`
}

func (q *Queries) CompleteStep(ctx context.Context, arg CompleteStepParams) error {
	_, err := q.db.Exec(ctx, completeStep, arg.Output, arg.ID)
	return err
}

const failStep = `-- name: FailStep :exec
UPDATE job_steps
SET status = 'failed', error = $1, completed_at = now(), updated_at = now()
WHERE id = $2
`

type FailStepParams struct {
	Error string    `json:"error"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) FailStep(ctx context.Context, arg FailStepParams) error {
	_, err := q.db.Exec(ctx, failStep, arg.Error, arg.ID)
	return err
}

const getStepsByJobID = `-- name: GetStepsByJobID :many
SELECT id, job_id, name, sequence, status, error, input, output, started_at, completed_at, created_at, updated_at FROM job_steps
WHERE job_id = $1
ORDER BY sequence ASC, created_at ASC
`

func (q *Queries) GetStepsByJobID(ctx context.Context, jobID uuid.UUID) ([]JobStep, error) {
	rows, err := q.db.Query(ctx, getStepsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobStep
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Name,
			&i.Sequence,
			&i.Status,
			&i.Error,
			&i.Input,
			&i.Output,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startStep = `-- name: StartStep :one
INSERT INTO job_steps (job_id, name, sequence, status, input, started_at)
VALUES ($1, $2, $3, 'running', $4, now())
RETURNING id, job_id, name, sequence, status, error, input, output, started_at, completed_at, created_at, updated_at
`

type StartStepParams struct {
	JobID    uuid.UUID       `json:"job_id"`
	Name     string          `json:"name"`
	Sequence int32           `json:"sequence"`
	Input    json.RawMessage `json:"input"`
}

func (q *Queries) StartStep(ctx context.Context, arg StartStepParams) (JobStep, error) {
	row := q.db.QueryRow(ctx, startStep,
		arg.JobID,
		arg.Name,
		arg.Sequence,
		arg.Input,
	)
	var i JobStep
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Name,
		&i.Sequence,
		&i.Status,
		&i.Error,
		&i.Input,
		&i.Output,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
