name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: task lint
      - run: task build
      - run: go vet ./...
      - run: task test:cover

  release:
    if: github.ref == 'refs/heads/main'
    needs: ci
    permissions:
      contents: write
    uses: laenen-partners/gh-action-scripts/.github/workflows/release.yaml@main
